runtime: php55
api_version: 1

handlers:
- url: /
  script: index.php
  
- url: /style.css
  script: style.css

- url: /index\.html
  script: index.php

- url: /stylesheets
  script: style.css

- url: /.*
  script: index.php
